// Mocks generated by Mockito 5.3.0 from annotations
// in ditonton/test/presentation/bloc/movie_watchlist_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i4;
import 'package:ditonton/common/failure.dart' as _i8;
import 'package:ditonton/domain/entities/movie_detail.dart' as _i9;
import 'package:ditonton/domain/entities/tv_series_detail.dart' as _i10;
import 'package:ditonton/domain/repositories/movie_repository.dart' as _i2;
import 'package:ditonton/domain/repositories/tv_series_repository.dart' as _i3;
import 'package:ditonton/domain/usecases/get_watchlist_status.dart' as _i5;
import 'package:ditonton/domain/usecases/remove_watchlist.dart' as _i11;
import 'package:ditonton/domain/usecases/save_watchlist.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMovieRepository_0 extends _i1.SmartFake
    implements _i2.MovieRepository {
  _FakeMovieRepository_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeTVSeriesRepository_1 extends _i1.SmartFake
    implements _i3.TVSeriesRepository {
  _FakeTVSeriesRepository_1(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeEither_2<L, R> extends _i1.SmartFake implements _i4.Either<L, R> {
  _FakeEither_2(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [GetWatchListStatus].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchListStatus extends _i1.Mock
    implements _i5.GetWatchListStatus {
  MockGetWatchListStatus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MovieRepository get movieRepository => (super.noSuchMethod(
          Invocation.getter(#movieRepository),
          returnValue:
              _FakeMovieRepository_0(this, Invocation.getter(#movieRepository)))
      as _i2.MovieRepository);
  @override
  _i3.TVSeriesRepository get tvSeriesRepository =>
      (super.noSuchMethod(Invocation.getter(#tvSeriesRepository),
              returnValue: _FakeTVSeriesRepository_1(
                  this, Invocation.getter(#tvSeriesRepository)))
          as _i3.TVSeriesRepository);
  @override
  _i6.Future<bool> executeMovie(int? id) =>
      (super.noSuchMethod(Invocation.method(#executeMovie, [id]),
          returnValue: _i6.Future<bool>.value(false)) as _i6.Future<bool>);
  @override
  _i6.Future<bool> executeTvSeries(int? id) =>
      (super.noSuchMethod(Invocation.method(#executeTvSeries, [id]),
          returnValue: _i6.Future<bool>.value(false)) as _i6.Future<bool>);
}

/// A class which mocks [SaveWatchlist].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveWatchlist extends _i1.Mock implements _i7.SaveWatchlist {
  MockSaveWatchlist() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MovieRepository get movieRepository => (super.noSuchMethod(
          Invocation.getter(#movieRepository),
          returnValue:
              _FakeMovieRepository_0(this, Invocation.getter(#movieRepository)))
      as _i2.MovieRepository);
  @override
  _i3.TVSeriesRepository get tvSeriesRepository =>
      (super.noSuchMethod(Invocation.getter(#tvSeriesRepository),
              returnValue: _FakeTVSeriesRepository_1(
                  this, Invocation.getter(#tvSeriesRepository)))
          as _i3.TVSeriesRepository);
  @override
  _i6.Future<_i4.Either<_i8.Failure, String>> executeMovie(
          _i9.MovieDetail? movie) =>
      (super.noSuchMethod(Invocation.method(#executeMovie, [movie]),
              returnValue: _i6.Future<_i4.Either<_i8.Failure, String>>.value(
                  _FakeEither_2<_i8.Failure, String>(
                      this, Invocation.method(#executeMovie, [movie]))))
          as _i6.Future<_i4.Either<_i8.Failure, String>>);
  @override
  _i6.Future<_i4.Either<_i8.Failure, String>> executeTvSeries(
          _i10.TvSeriesDetail? tvSeries) =>
      (super.noSuchMethod(Invocation.method(#executeTvSeries, [tvSeries]),
              returnValue: _i6.Future<_i4.Either<_i8.Failure, String>>.value(
                  _FakeEither_2<_i8.Failure, String>(
                      this, Invocation.method(#executeTvSeries, [tvSeries]))))
          as _i6.Future<_i4.Either<_i8.Failure, String>>);
}

/// A class which mocks [RemoveWatchlist].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveWatchlist extends _i1.Mock implements _i11.RemoveWatchlist {
  MockRemoveWatchlist() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MovieRepository get movieRepository => (super.noSuchMethod(
          Invocation.getter(#movieRepository),
          returnValue:
              _FakeMovieRepository_0(this, Invocation.getter(#movieRepository)))
      as _i2.MovieRepository);
  @override
  _i3.TVSeriesRepository get tvSeriesRepository =>
      (super.noSuchMethod(Invocation.getter(#tvSeriesRepository),
              returnValue: _FakeTVSeriesRepository_1(
                  this, Invocation.getter(#tvSeriesRepository)))
          as _i3.TVSeriesRepository);
  @override
  _i6.Future<_i4.Either<_i8.Failure, String>> executeMovie(
          _i9.MovieDetail? movie) =>
      (super.noSuchMethod(Invocation.method(#executeMovie, [movie]),
              returnValue: _i6.Future<_i4.Either<_i8.Failure, String>>.value(
                  _FakeEither_2<_i8.Failure, String>(
                      this, Invocation.method(#executeMovie, [movie]))))
          as _i6.Future<_i4.Either<_i8.Failure, String>>);
  @override
  _i6.Future<_i4.Either<_i8.Failure, String>> executeTvSeries(
          _i10.TvSeriesDetail? tvSeries) =>
      (super.noSuchMethod(Invocation.method(#executeTvSeries, [tvSeries]),
              returnValue: _i6.Future<_i4.Either<_i8.Failure, String>>.value(
                  _FakeEither_2<_i8.Failure, String>(
                      this, Invocation.method(#executeTvSeries, [tvSeries]))))
          as _i6.Future<_i4.Either<_i8.Failure, String>>);
}
